-- Run this file in the Supabase SQL editor. The quoted column names preserve
-- compatibility with the existing Entity Framework migrations and API.

create table if not exists public.users (
  "Id" uuid primary key,
  "Username" varchar(100) not null unique,
  "PasswordHash" text not null,
  "CreatedAt" timestamptz not null,
  "IngestionToken" varchar(64) not null unique
);

create table if not exists public.servers (
  "Id" varchar(200) primary key,
  "HostName" varchar(255) not null,
  "IpAddress" varchar(45),
  "LastHeartbeatAt" timestamptz not null,
  "OwnerUserId" uuid references public.users ("Id") on delete set null
);

create index if not exists "IX_servers_OwnerUserId"
  on public.servers ("OwnerUserId");

create table if not exists public.performance_metrics (
  "Id" bigint generated by default as identity primary key,
  "ServerId" varchar(200) not null
    references public.servers ("Id") on delete cascade,
  "Timestamp" timestamptz not null,
  "CpuUsagePct" real not null,
  "MemoryUsedBytes" bigint not null,
  "MemoryTotalBytes" bigint not null,
  "DiskUtilizationPct" real not null,
  "NetworkInBytesSec" bigint not null
);

create index if not exists "IX_performance_metrics_ServerId_Timestamp"
  on public.performance_metrics ("ServerId", "Timestamp" desc);

create table if not exists public.tags (
  "Name" varchar(50) primary key
);

create table if not exists public.server_tags (
  "ServerId" varchar(200) not null
    references public.servers ("Id") on delete cascade,
  "TagName" varchar(50) not null
    references public.tags ("Name") on delete cascade,
  primary key ("ServerId", "TagName")
);

create index if not exists "IX_server_tags_TagName"
  on public.server_tags ("TagName");

create table if not exists public.alert_events (
  "Id" bigint generated by default as identity primary key,
  "ServerId" varchar(200) not null
    references public.servers ("Id") on delete cascade,
  "OwnerUserId" uuid references public.users ("Id") on delete set null,
  "RuleKey" varchar(100) not null,
  "Severity" varchar(20) not null,
  "Status" varchar(20) not null,
  "Message" varchar(500) not null,
  "TriggerValue" double precision,
  "ThresholdValue" double precision,
  "TriggeredAt" timestamptz not null,
  "LastObservedAt" timestamptz not null,
  "ResolvedAt" timestamptz,
  "LastNotifiedAt" timestamptz
);

create index if not exists "IX_alert_events_OwnerUserId"
  on public.alert_events ("OwnerUserId");

create index if not exists "IX_alert_events_ServerId_RuleKey_Status"
  on public.alert_events ("ServerId", "RuleKey", "Status");

create index if not exists "IX_alert_events_LastObservedAt"
  on public.alert_events ("LastObservedAt");

create table if not exists public.agent_tokens (
  "Id" uuid primary key,
  "ServerId" varchar(200) not null
    references public.servers ("Id") on delete cascade,
  "OwnerUserId" uuid not null
    references public.users ("Id") on delete cascade,
  "Name" varchar(100) not null,
  "TokenHash" varchar(64) not null unique,
  "TokenSuffix" varchar(16) not null,
  "AllowedIpAddresses" varchar(1000),
  "CreatedAt" timestamptz not null,
  "LastUsedAt" timestamptz,
  "RevokedAt" timestamptz
);

create index if not exists "IX_agent_tokens_ServerId_OwnerUserId"
  on public.agent_tokens ("ServerId", "OwnerUserId");

create index if not exists "IX_agent_tokens_OwnerUserId"
  on public.agent_tokens ("OwnerUserId");

create table if not exists public.audit_logs (
  "Id" bigint generated by default as identity primary key,
  "OwnerUserId" uuid references public.users ("Id") on delete set null,
  "ActorType" varchar(50) not null,
  "Action" varchar(100) not null,
  "EntityType" varchar(100) not null,
  "EntityId" varchar(200),
  "Message" varchar(500),
  "IpAddress" varchar(45),
  "CreatedAt" timestamptz not null
);

create index if not exists "IX_audit_logs_OwnerUserId_CreatedAt"
  on public.audit_logs ("OwnerUserId", "CreatedAt" desc);

drop function if exists public.netrascope_ingest_metric(
  text, timestamptz, real, bigint, bigint, real, bigint, text, uuid
);

create function public.netrascope_ingest_metric(
  p_server_id text,
  p_timestamp timestamptz,
  p_cpu_usage_pct real,
  p_memory_used_bytes bigint,
  p_memory_total_bytes bigint,
  p_disk_utilization_pct real,
  p_network_in_bytes_sec bigint,
  p_ip_address text,
  p_owner_user_id uuid
)
returns boolean
language plpgsql
set search_path = ''
as $$
begin
  insert into public.servers (
    "Id", "HostName", "IpAddress", "LastHeartbeatAt", "OwnerUserId"
  )
  values (
    p_server_id, p_server_id, p_ip_address, now(), p_owner_user_id
  )
  on conflict ("Id") do update set
    "HostName" = excluded."HostName",
    "IpAddress" = excluded."IpAddress",
    "LastHeartbeatAt" = excluded."LastHeartbeatAt",
    "OwnerUserId" = excluded."OwnerUserId"
  where public.servers."OwnerUserId" is null
     or public.servers."OwnerUserId" = p_owner_user_id;

  if not found then
    return false;
  end if;

  insert into public.performance_metrics (
    "ServerId",
    "Timestamp",
    "CpuUsagePct",
    "MemoryUsedBytes",
    "MemoryTotalBytes",
    "DiskUtilizationPct",
    "NetworkInBytesSec"
  )
  values (
    p_server_id,
    p_timestamp,
    p_cpu_usage_pct,
    p_memory_used_bytes,
    p_memory_total_bytes,
    p_disk_utilization_pct,
    p_network_in_bytes_sec
  );

  return true;
end;
$$;

create or replace function public.netrascope_replace_server_tags(
  p_server_id text,
  p_owner_user_id uuid,
  p_tags text[]
)
returns boolean
language plpgsql
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.servers
    where "Id" = p_server_id and "OwnerUserId" = p_owner_user_id
  ) then
    return false;
  end if;

  delete from public.server_tags where "ServerId" = p_server_id;

  insert into public.tags ("Name")
  select distinct tag_name
  from unnest(p_tags) as input(tag_name)
  on conflict ("Name") do nothing;

  insert into public.server_tags ("ServerId", "TagName")
  select p_server_id, tag_name
  from unnest(p_tags) as input(tag_name);

  return true;
end;
$$;

alter table public.users enable row level security;
alter table public.servers enable row level security;
alter table public.performance_metrics enable row level security;
alter table public.tags enable row level security;
alter table public.server_tags enable row level security;
alter table public.alert_events enable row level security;
alter table public.agent_tokens enable row level security;
alter table public.audit_logs enable row level security;

revoke all on table public.users from anon, authenticated;
revoke all on table public.servers from anon, authenticated;
revoke all on table public.performance_metrics from anon, authenticated;
revoke all on table public.tags from anon, authenticated;
revoke all on table public.server_tags from anon, authenticated;
revoke all on table public.alert_events from anon, authenticated;
revoke all on table public.agent_tokens from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;
revoke execute on function public.netrascope_ingest_metric(
  text, timestamptz, real, bigint, bigint, real, bigint, text, uuid
) from public, anon, authenticated;
revoke execute on function public.netrascope_replace_server_tags(
  text, uuid, text[]
) from public, anon, authenticated;

grant usage on schema public to service_role;
grant all on table public.users to service_role;
grant all on table public.servers to service_role;
grant all on table public.performance_metrics to service_role;
grant all on table public.tags to service_role;
grant all on table public.server_tags to service_role;
grant all on table public.alert_events to service_role;
grant all on table public.agent_tokens to service_role;
grant all on table public.audit_logs to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.netrascope_ingest_metric(
  text, timestamptz, real, bigint, bigint, real, bigint, text, uuid
) to service_role;
grant execute on function public.netrascope_replace_server_tags(
  text, uuid, text[]
) to service_role;
