// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetraScope.Core.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetraScope.Core.Data.Migrations
{
    [DbContext(typeof(NetraDbContext))]
    [Migration("20260617064218_AddMetricRollups")]
    partial class AddMetricRollups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetraScope.Core.Entities.AgentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedIpAddresses")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenSuffix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ServerId", "OwnerUserId");

                    b.ToTable("agent_tokens", (string)null);
                });

            modelBuilder.Entity("NetraScope.Core.Entities.AlertEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("ThresholdValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TriggerValue")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastObservedAt");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ServerId", "RuleKey", "Status");

                    b.ToTable("alert_events", (string)null);
                });

            modelBuilder.Entity("NetraScope.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("NetraScope.Core.Entities.MetricRollup", b =>
                {
                    b.Property<string>("ServerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Granularity")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("CpuAvgPct")
                        .HasColumnType("real");

                    b.Property<float>("CpuMaxPct")
                        .HasColumnType("real");

                    b.Property<float>("DiskAvgPct")
                        .HasColumnType("real");

                    b.Property<float>("DiskMaxPct")
                        .HasColumnType("real");

                    b.Property<long>("MemoryTotalMaxBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryUsedAvgBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryUsedMaxBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkInAvgBytesSec")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkInMaxBytesSec")
                        .HasColumnType("bigint");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.HasKey("ServerId", "Granularity", "BucketStart");

                    b.HasIndex("Granularity", "BucketStart");

                    b.ToTable("metric_rollups", (string)null);
                });

            modelBuilder.Entity("NetraScope.Core.Entities.PerformanceMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("CpuUsagePct")
                        .HasColumnType("real");

                    b.Property<float>("DiskUtilizationPct")
                        .HasColumnType("real");

                    b.Property<long>("MemoryTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkInBytesSec")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("performance_metrics", (string)null);
                });

            modelBuilder.Entity("NetraScope.Core.Entities.Server", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("NetraScope.Core.Entities.ServerTag", b =>
                {
                    b.Property<string>("ServerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TagName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ServerId", "TagName");

                    b.HasIndex("TagName");

                    b.ToTable("server_tags", (string)null);
                });

            modelBuilder.Entity("NetraScope.Core.Entities.Tag", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("NetraScope.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IngestionToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IngestionToken")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NetraScope.Core.Entities.AgentToken", b =>
                {
                    b.HasOne("NetraScope.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetraScope.Core.Entities.Server", "Server")
                        .WithMany("AgentTokens")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NetraScope.Core.Entities.AlertEvent", b =>
                {
                    b.HasOne("NetraScope.Core.Entities.Server", "Server")
                        .WithMany("AlertEvents")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NetraScope.Core.Entities.MetricRollup", b =>
                {
                    b.HasOne("NetraScope.Core.Entities.Server", "Server")
                        .WithMany("MetricRollups")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NetraScope.Core.Entities.PerformanceMetric", b =>
                {
                    b.HasOne("NetraScope.Core.Entities.Server", "Server")
                        .WithMany("Metrics")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NetraScope.Core.Entities.Server", b =>
                {
                    b.HasOne("NetraScope.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NetraScope.Core.Entities.ServerTag", b =>
                {
                    b.HasOne("NetraScope.Core.Entities.Server", "Server")
                        .WithMany("ServerTags")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetraScope.Core.Entities.Tag", "Tag")
                        .WithMany("ServerTags")
                        .HasForeignKey("TagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("NetraScope.Core.Entities.Server", b =>
                {
                    b.Navigation("AgentTokens");

                    b.Navigation("AlertEvents");

                    b.Navigation("MetricRollups");

                    b.Navigation("Metrics");

                    b.Navigation("ServerTags");
                });

            modelBuilder.Entity("NetraScope.Core.Entities.Tag", b =>
                {
                    b.Navigation("ServerTags");
                });
#pragma warning restore 612, 618
        }
    }
}
